### PR TITLE
feature/use_textarea_to_support_multiple_line

### LINKED ISSUE #121: use textarea to support multiple line in jq filter
Hi there, thanks for this great handy tool to learn and practice jq. 

I have a user experience optimization proposal. If the input box of the jq filter can support multi-line input, it will be more convenient. Currently in my daily development, in scenarios involving multiple lines of jq, I use jq -f xxx.jq xxx.json instead.
If you think there is no problem, I can mention MR to complete this optimization

### PR DESCRIPTION
**Pull request by vuuihc**
may resolve #121

### CODE REVIEW

**Comment by vuuihc** [comment]
@owenthereal Hi Owen, can you review this PR when you have time?

**Comment by vuuihc** [comment]
Cool, looking forward to going online

**Comment by owenthereal** [comment]
@vuuihc The changes are up. Can you check if you like this now :) ?

**Comment by vuuihc** [comment]
@owenthereal perfect!

**Pull request closed without merging**
