### PR TITLE
Restrict resource usage when shelling out `jq`

### PR DESCRIPTION
**Pull request by owenthereal**
Restrict resource usage when shelling out `jq`

### CODE REVIEW

**Comment by wader** [comment]
jqjq fails with out of memory now 😬😢 https://jqplay.org/s/UwAvCZmbi2r

**Comment by wader** [comment]
Played around a bit and 20MB seem to be enough, at least when running in container like this `docker run -m 20m ...`

**Comment by owenthereal** [comment]
> Played around a bit and 20MB seem to be enough, at least when running in container like this docker run -m 20m ...

No worries. I will bump it to 20MB 😄

**Comment by wader** [comment]
🥳 mostly because of the jqplay link on the jqjq repo page 😊

**Pull request merged**
